version: "3"

services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - 3000:3000
      - 587:587
    networks:
      - grafana_network
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana.ini:/etc/grafana/grafana.ini
    environment:
      - GF_RENDERING_SERVER_URL=http://renderer:8081/render
      - GF_RENDERING_CALLBACK_URL=http://grafana:3000/
      - GF_LOG_FILTERS=rendering:debug

    depends_on:
      - influxdb
      - loki
      - renderer
######################
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    restart: always
    ports:
      - 8086:8086
    networks:
      - grafana_network
    volumes:
      - influxdb_data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin 
      - DOCKER_INFLUXDB_INIT_PASSWORD=sync2016 
      - DOCKER_INFLUXDB_INIT_ORG=filtanet
      - DOCKER_INFLUXDB_INIT_BUCKET=telegraf 
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=iwyuJgH8Lmr8zYgs2aAQWnk1Y9oP5wPk_Gzu2QBf_BVtkY_tCsi3AM7wn5N5m6Cn2iVr-sSG6FZ3xHnTWjq9NA==
####################
  loki:
    image: grafana/loki
    container_name: loki
    restart: always
    ports:
      - 3100:3100
    networks:
      - grafana_network
    volumes:
      - loki_data:/var/lib/loki
    command: -config.file=/etc/loki/local-config.yaml
########################
  promtail:
    image: grafana/promtail
    container_name: promtail
    restart: always
    volumes:
      - /var/log/:/var/log/:ro
      - /home/:/home_server:ro
      - /root/:/root_user:ro
      - ./promtail.yml:/etc/promtail/promtail.yml
      - promtail-data:/tmp
    command: -config.file=/etc/promtail/promtail.yml
    depends_on:
      - loki
    networks:
      - grafana_network
###########################
  renderer:
    image: grafana/grafana-image-renderer:latest
    container_name: renderer
    restart: always
#    volumes:
#      - ./config.json:/usr/src/app/config.json
#    depends_on:
#      - grafana
    ports:
      - 8081
    networks:
      - grafana_network


networks:
  grafana_network:

volumes:
  grafana_data:
  influxdb_data:
  loki_data:
  promtail-data: